#!/usr/bin/env bash

set -uo pipefail;

echo 'Usage: tenv <command> [<options>]

Commands:
   install       Install tenv dependencies (tfenv and tofuenv)
   uninstall     Uninstall tenv dependencies (tfenv and tofuenv)
   tofu          List of tofuenv commands
   tf            List of tfenv commands
   version-name  Print current version of tenv
   help          Show the tenv help
';

exit 0;